export enum ERROR {
  // user
  NO_USERNAME,
  NAME_TAKEN,
  INVALID_PLAYER_NAME_LENGTH,
  PLAYER_NOT_FOUND,
  // room
  ALREADY_IN_ROOM,
  ROOM_NOT_FOUND,
  ROOM_FULL,
  INVALID_ROOM_NAME,
  NOT_OWNER,
  CANNOT_START,
  // game
  GAME_IN_PROGRESS,
  GAME_NOT_RUNNING,
  NOT_YOUR_TURN,
  EXCHANGE_IS_FORBIDDEN,
  NOT_ENOUGH_CARDS,
  LIMITED_CARDS_EXCEEDED,
  // emotes
  UNKNOWN_EMOTE,
  THROTTLED,
}
