export enum ERROR {
  // user
  NO_USERNAME = 'NO_USERNAME',
  NAME_TAKEN = 'NAME_TAKEN',
  INVALID_PLAYER_NAME_LENGTH = 'INVALID_PLAYER_NAME_LENGTH',
  PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND',
  // room
  ALREADY_IN_ROOM = 'ALREADY_IN_ROOM',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ROOM_FULL = 'ROOM_FULL',
  INVALID_ROOM_NAME = 'INVALID_ROOM_NAME',
  NOT_OWNER = 'NOT_OWNER',
  CANNOT_START = 'CANNOT_START',
  // game
  GAME_IN_PROGRESS = 'GAME_IN_PROGRESS',
  GAME_NOT_RUNNING = 'GAME_NOT_RUNNING',
  NOT_YOUR_TURN = 'NOT_YOUR_TURN',
  EXCHANGE_IS_FORBIDDEN = 'EXCHANGE_IS_FORBIDDEN',
  NOT_ENOUGH_CARDS = 'NOT_ENOUGH_CARDS',
  LIMITED_CARDS_EXCEEDED = 'LIMITED_CARDS_EXCEEDED',
  // trade
  TRADE_NOT_ALLOWED = 'TRADE_NOT_ALLOWED',
  TRADE_ALREADY_ACTIVE = 'TRADE_ALREADY_ACTIVE',
  TRADE_NOT_ACTIVE = 'TRADE_NOT_ACTIVE',
  TRADE_NOT_LOCKED = 'TRADE_NOT_LOCKED',
  INVALID_TRADE_TARGET = 'INVALID_TRADE_TARGET',
  // emotes
  UNKNOWN_EMOTE = 'UNKNOWN_EMOTE',
  THROTTLED = 'THROTTLED',
}
